version: "3.9"
services:
  reina:
    container_name: Reina
    restart: always
    image: no767/reina:edge-alpine
    env_file:
      - .env-example # Re-name this to .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 3
        window: 120s
      mode: replicated
    depends_on:
      - postgres

  postgres:
    container_name: Reina-Postgres
    image: postgres:14.5 # Use the Alpine version if you are running low on storage
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=Reina
      - POSTGRES_DB=Reina
    volumes:
      - prod_postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  prod_postgres_volume: