version: "3.9"
services:
  postgres:
    container_name: Reina-Postgres
    image: no767/reina-postgres:edge
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  reina:
    container_name: Reina
    image: no767/reina:edge
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 5
        window: 120s
      mode: replicated
    command: sh -c '/Reina/wait-for postgres:5432 -- echo "[Wait-for] PostgreSQL is fully ready. Starting up Reina" && /Reina/start.sh'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_volume: