[tool.poetry]
name = "Reina"
version = "0.1.0"
description = "A fork of Beryl built for production and enterprise use"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
py-cord = {version = "2.1.1", extras = ["voice"]}
aiodns = "^3.0.0"
cchardet = "^2.1.7"
python-dotenv = "^0.20.0"
uvloop = "^0.16.0"
requests = "^2.28.1"
pysimdjson = "^5.0.1"
disquest-utils = "^1.1.0"
ffmpeg-python = "^0.2.0"
orjson = "^3.8.0"
python-dateutil = "^2.8.2"
beryl-events-utils = "^2.0.1"
rin-exceptions = "^1.0.2"
Brotli = "^1.0.9"
gql = {extras = ["aiohttp"], version = "^3.4.0"}
numpy = "^1.23.2"
asyncpraw = "^7.5.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
pyinstrument = "^4.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
