#!/usr/bin/env bash

# Bot Token
if [[ -v REINA_TOKEN ]]; then
    echo "Reina_Token=${REINA_TOKEN}" >> /Reina/Bot/.env
else
    echo "Missing bot token! REINA_TOKEN environment variable is not set."
    exit 1;
fi

if [[ -v REINA_DEV_TOKEN ]]; then
    echo "Reina_Dev_Token=${REINA_DEV_TOKEN}" >> /Reina/Bot/.env
fi

# Hypixel API Keys
if [[ -v HYPIXEL_API_KEY ]]; then
    echo "Hypixel_API_Key=${HYPIXEL_API_KEY}" >> /Reina/Bot/.env
else
    echo "Missing Hypixel API key! HYPIXEL_API_KEY environment variable is not set."
fi 

if [[ -v TENOR_API_KEY ]]; then
    echo "Tenor_API_Key=${TENOR_API_KEY}" >> /Reina/Bot/.env
else
    echo "Missing Tenor API key! TENOR_API_KEY environment variable is not set."
fi 

if [[ -v REDDIT_ID ]]; then
    echo "Reddit_ID=${REDDIT_ID}" >> /Reina/Bot/.env
else
    echo "Missing Reddit ID! REDDIT_ID environment variable is not set."
fi 
# Reddit Secret
if [[ -v REDDIT_SECRET ]]; then
    echo "Reddit_Secret=${REDDIT_SECRET}" >> /Reina/Bot/.env
else
    echo "Missing Reddit secret! REDDIT_SECRET environment variable is not set."
fi

if [[ -v POSTGRES_PASSWORD ]]; then
    echo "Postgres_Password=${POSTGRES_PASSWORD}" >> /Reina/Bot/.env
else
    echo "Missing Postgres_Password env var! Postgres_Password environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_IP ]]; then
    echo "Postgres_IP=${POSTGRES_IP}" >> /Reina/Bot/.env
else
    echo "Missing Postgres_IP env var! POSTGRES_IP environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_USER ]]; then
    echo "Postgres_User=${POSTGRES_USER}" >> /Reina/Bot/.env
else
    echo "Missing Postgres_User env var! POSTGRES_USER environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_DB ]]; then
    echo "Postgres_Database=${POSTGRES_DB}" >> /Reina/Bot/.env
else
    echo "Missing Postgres_Database env var! POSTGRES_DB environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PORT ]]; then
    echo "Postgres_Port=${POSTGRES_PORT}" >> /Reina/Bot/.env
else
    echo "Missing Postgres_Port env var ! POSTGRES_PORT environment variable is not set."
    exit 1;
fi

REINA_FIRST_START_CHECK="REINA_FIRST_START"

if [ ! -f $REINA_FIRST_START_CHECK ]; then
    touch $REINA_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN REINA USING DOCKER!' >> $REINA_FIRST_START_CHECK
    python3 /Reina/postgres-seeder.py
fi

exec python3 /Reina/Bot/reina.py