#!/usr/bin/env bash

# Bot Token
if [[ -v REINA_TOKEN ]]; then
    echo "Reina_Token=${REINA_TOKEN}" >> /Reina/Bot/.env
else
    echo "Missing bot token! REINA_TOKEN environment variable is not set."
    exit 1;
fi

if [[ -v REINA_DEV_TOKEN ]]; then
    echo "Reina_Dev_Token=${REINA_DEV_TOKEN}" >> /Reina/Bot/.env
fi

# Hypixel API Keys
if [[ -v HYPIXEL_API_KEY ]]; then
    echo "Hypixel_API_Key=${HYPIXEL_API_KEY}" >> /Reina/Bot/.env
else
    echo "Missing Hypixel API key! HYPIXEL_API_KEY environment variable is not set."
fi 

if [[ -v TENOR_API_KEY ]]; then
    echo "Tenor_API_Key=${TENOR_API_KEY}" >> /Reina/Bot/.env
else
    echo "Missing Tenor API key! TENOR_API_KEY environment variable is not set."
fi 

if [[ -v REDDIT_ID ]]; then
    echo "Reddit_ID=${REDDIT_ID}" >> /Reina/Bot/.env
else
    echo "Missing Reddit ID! REDDIT_ID environment variable is not set."
fi 
# Reddit Secret
if [[ -v REDDIT_SECRET ]]; then
    echo "Reddit_Secret=${REDDIT_SECRET}" >> /Reina/Bot/.env
else
    echo "Missing Reddit secret! REDDIT_SECRET environment variable is not set."
fi

if [[ -v POSTGRES_PASSWORD ]]; then
    echo "Postgres_Password=${POSTGRES_PASSWORD}" >> /Reina/Bot/.env
else
    echo "Missing POSTGRES_PASSWORD env var! Postgres_Password environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_HOST ]]; then
    echo "Postgres_Host=${POSTGRES_HOST}" >> /Reina/Bot/.env
else
    echo "Missing POSTGRES_HOST env var! Postgres_Host environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_USER ]]; then
    echo "Postgres_Username=${POSTGRES_USER}" >> /Reina/Bot/.env
else
    echo "Missing POSTGRES_USER env var! Postgres_User environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_REINA_DB ]]; then
    echo "Postgres_Reina_Database=${POSTGRES_REINA_DB}" >> /Reina/Bot/.env
else
    echo "Missing POSTGRES_REINA_DB env var! Postgres_Reina_Database environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PORT ]]; then
    echo "Postgres_Port=${POSTGRES_PORT}" >> /Reina/Bot/.env
else
    echo "Missing POSTGRES_PORT env var ! Postgres_Port environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_HOST ]]; then
    echo "Redis_Host=${REDIS_HOST}" >> /Reina/Bot/.env
else
    echo "Missing REDIS_HOST env var ! Redis_Host environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_PORT ]]; then
    echo "Redis_Port=${REDIS_PORT}" >> /Reina/Bot/.env
else
    echo "Missing REDIS_PORT env var ! Redis_Port environment variable is not set."
    exit 1;
fi

REINA_FIRST_START_CHECK="REINA_FIRST_START"

if [ ! -f $REINA_FIRST_START_CHECK ]; then
    touch $REINA_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN REINA USING DOCKER!' >> $REINA_FIRST_START_CHECK
    python3 /Reina/postgres-seeder.py
fi

exec python3 /Reina/Bot/reina.py