name: Docker Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  Build-Alpine-GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/no767/reina
          tags: |
            type=semver,pattern={{raw}},suffix=-alpine
            type=semver,pattern={{version}},suffix=-alpine
            type=semver,pattern={{major}}.{{minor}},suffix=-alpine
            type=semver,pattern={{major}},suffix=-alpine
            type=edge,branch=dev,suffix=-alpine
          flavor: |
            latest=false

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-alpine-ghcr-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-alpine-ghcr-
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Alpine-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-alpine-ghcr

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-alpine-ghcr /tmp/.buildx-cache

  Build-Debian-GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/no767/reina
          tags: |
            type=semver,pattern={{version}},suffix=-bullseye
            type=semver,pattern={{major}}.{{minor}},suffix=-bullseye
            type=semver,pattern={{major}},suffix=-bullseye
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=dev,suffix=-bullseye
            type=edge,branch=dev

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v2-debian-ghcr-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v2-debian-ghcr-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Debian-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-debian-ghcr

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-debian-ghcr /tmp/.buildx-cache

  Build-Alpine-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/reina
          tags: |
            type=semver,pattern={{version}},suffix=-alpine
            type=semver,pattern={{major}}.{{minor}},suffix=-alpine
            type=semver,pattern={{major}},suffix=-alpine
            type=edge,branch=dev,suffix=-alpine
          flavor: |
            latest=false

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-alpine-hub-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-alpine-hub-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Alpine-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-alpine-hub

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-alpine-hub /tmp/.buildx-cache

  Build-Debian-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/reina
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}},suffix=-bullseye
            type=semver,pattern={{major}}.{{minor}},suffix=-bullseye
            type=semver,pattern={{major}},suffix=-bullseye
            type=edge,branch=dev,suffix=-bullseye
            type=edge,branch=dev

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v2-debian-hub-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v2-debian-hub-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Debian-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-debian-hub

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-debian-hub /tmp/.buildx-cache

  Build-Reina-Postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/reina-postgres
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=dev

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.0.10
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-reina-postgres-hub-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-reina-postgres-hub-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Postgres-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-reina-postgres

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-reina-postgres /tmp/.buildx-cache